Add Test for Books
AgroFix/book-store pull request #15
Opened 2024-01-09 15:34 UTC by AgroFix

2024-01-09 18:53 UTC, nshtykh approved these changes
GJ!

2024-01-09 18:53 UTC, nshtykh commented on src/test/resources/database/categories/delete-books-categories.sql
> +DELETE FROM books_categories
Add an empty line

2024-01-09 18:53 UTC, nshtykh commented on src/test/resources/database/categories/delete-categories.sql
> +DELETE FROM categories
Add an empty line

2024-01-11 11:20 UTC, yevheniisynytsia requested changes
Well done! small changes to go!

2024-01-11 11:20 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookstore/controller/BookControllerTest.java
> +    private static BookResponseDto bookResponseDto;
move it down a bit, so that you have more logical order

2024-01-11 11:20 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookstore/controller/BookControllerTest.java
> +        List<BookResponseDto> actual = Arrays.asList(objectMapper
you can readValue as list, no need to use `asList`

2024-01-11 11:20 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookstore/repository/BookRepositoryTest.java
> +        List<Book> books = List.of(firstBook, secondBook);
why do you need two books, if you explicitly specify to test only one id

2024-01-11 11:20 UTC, yevheniisynytsia commented on src/test/java/mate/academy/bookstore/service/impl/BookServiceTest.java
> +    @Mock
add space to separate mocks from other fields

2024-01-15 07:57 UTC, yevheniisynytsia approved these changes
:fire:

2024-01-18 13:12 UTC, merged