Added Liquibase support, implemented soft delete concept for the Book…
AgroFix/book-store pull request #3
Opened 2023-12-12 18:18 UTC by AgroFix

… entity, added delete, update methods

2023-12-12 19:42 UTC, annton-shakur approved these changes
Good job!

2023-12-13 07:17 UTC, kshuryhin requested changes
Good job, but there are some points to consider

2023-12-13 07:17 UTC, kshuryhin commented on src/main/java/mate/academy/bookstore/model/Book.java
> +@Where(clause = "is_deleted=false")
'org.hibernate.annotations.Where' is deprecated

2023-12-13 07:17 UTC, kshuryhin commented on src/main/java/mate/academy/bookstore/controller/BookController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
Why do we use `NO_CONTENT` status for the **PUT** method?

2023-12-13 15:38 UTC, vovasalyha approved these changes
LGTM

2023-12-13 15:40 UTC, merged