Added spring-boot-starter-security, SecurityConfig, UserDetailsServic…
AgroFix/book-store pull request #7
Opened 2023-12-21 21:34 UTC by AgroFix

…e, Role entity, RoleRepository

2023-12-22 10:33 UTC, BohdanTrue approved these changes
LGTM

2023-12-26 09:09 UTC, d1sam requested changes
Good job, but some changes should be done according to my comment

2023-12-26 09:09 UTC, d1sam commented on src/main/java/mate/academy/bookstore/config/SecurityConfig.java
> +                                .requestMatchers("/api/auth/**", "/error", "/swagger-ui/**")
```suggestion
                                .requestMatchers("/api/auth/**", "/error", "/swagger-ui/**", "/v3/api-docs/**")
```

2023-12-26 09:09 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-26 09:09 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-26 09:09 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-26 09:09 UTC, d1sam commented on src/main/resources/db/changelog/changes/08-insert-users-roles.yaml
try to use `valueComputed`

2023-12-26 09:09 UTC, d1sam commented on src/main/resources/db/changelog/changes/06-create-users-roles-table.yaml
make pairs user_id + role_id unique

2023-12-26 17:17 UTC, yevheniisynytsia requested changes

2023-12-26 17:17 UTC, yevheniisynytsia commented on src/main/resources/db/changelog/changes/09-insert-users-roles.yaml
> +              - column: {name: role_id, valueComputed: "1"}
valueComputed means that you can pass a function to the value. It can be a SQL query to get some results

2023-12-26 17:45 UTC, AgroFix commented on src/main/resources/db/changelog/changes/09-insert-users-roles.yaml
> +              - column: {name: role_id, valueComputed: "1"}
My bad😅

2023-12-27 08:01 UTC, d1sam requested changes
good job, but some changes in your migration files should be done.

2023-12-27 08:01 UTC, d1sam commented on src/main/resources/db/changelog/changes/06-create-roles-table.yaml
> +                    nullable: false
when column is primary key constraint nullable is redundant, because primary key is unique + not null. just for your info :)

2023-12-27 08:01 UTC, d1sam commented on src/main/resources/db/changelog/changes/07-create-users-roles-table.yaml
> +                    references: users(id)
when you set `unique` -> `true` to `user_id` and `role_id`, it means that for example user with id = 1 can be inserted to this table only once. You should not do this way. You should add **composite** [key](https://www.simplilearn.com/tutorials/sql-tutorial/composite-key-in-sql#:~:text=View%20More-,What%20Is%20a%20Composite%20Key%20in%20SQL%3F,can%20uniquely%20identify%20any%20record.)

2023-12-27 08:01 UTC, d1sam commented on src/main/resources/db/changelog/changes/09-insert-users-roles.yaml
> +      author: AgroFix
When you use `valueComputed` it's a good practice to use `pre-conditions`.

2023-12-27 15:55 UTC, vovasalyha approved these changes
GJ, but pay attention to commit messages. `Fixed some points` is a bad example.

2023-12-27 15:59 UTC, merged