Jwt
AgroFix/book-store pull request #9
Opened 2023-12-25 16:55 UTC by AgroFix

2023-12-26 13:55 UTC, andrii-hoienko requested changes

2023-12-26 13:55 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/security/CustomUserDetailsService.java
> +    private static final String USER_NOT_FOUND_BY_EMAIL_MSG = "Can't find user by email: ";
```suggestion
    private static final String USER_NOT_FOUND_BY_EMAIL_MSG = "Can't find user by email: %s";
```

2023-12-26 13:55 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/security/CustomUserDetailsService.java
> +                        () -> new UsernameNotFoundException(USER_NOT_FOUND_BY_EMAIL_MSG + email));
Better to use String.format in such cases

2023-12-26 13:55 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
> +            return Optional.of(bearerToken.substring(7));
Magic number

2023-12-26 13:55 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith("Bearer ")) {
Please make "Bearer " constant

2023-12-26 13:55 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/security/JwtUtil.java
> +            throw new JwtException("Expired or invalid JWT token");
Please be consistent, in some cases you extract error messages in constants in some cases not, please decide on behavior with error messages and apply it to all project

2023-12-26 13:55 UTC, andrii-hoienko commented on src/main/java/mate/academy/bookstore/model/User.java
> +    private Set<Role> roles;
Please exclude relations from equals/hashCode and toString

2023-12-27 11:14 UTC, d1sam requested changes
Good job, but some changes should be done and why I see changes from previous prs in this pr?

2023-12-27 11:14 UTC, d1sam commented on src/main/resources/db/changelog/changes/08-insert-users-roles.yaml
it's better to insert user by valueComputed and preConditions, example:
 ```
     preConditions:
        - sqlCheck:
            expectedResult: 1
            sql: SELECT COUNT(*) FROM users WHERE email='admin@example.com'
        - sqlCheck:
            expectedResult: 1
            sql: SELECT COUNT(*) FROM roles WHERE name='ROLE_ADMIN'
      changes:
        - insert:
            tableName: user_role
            columns:
              - column:
                  name: user_id
                  valueComputed: (SELECT id FROM users WHERE email='admin@example.com')
              - column:
                  name: role_id
                  valueComputed: (SELECT id FROM roles WHERE name='ROLE_ADMIN')
```

2023-12-27 11:14 UTC, d1sam commented on src/main/resources/db/changelog/changes/06-create-users-roles-table.yaml
users_roles should have composite key.

2023-12-27 11:14 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-27 11:14 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-27 11:14 UTC, d1sam commented on src/main/java/mate/academy/bookstore/model/User.java
> +        return true;
```suggestion
        return !isDeleted;
```

2023-12-27 15:57 UTC, vovasalyha approved these changes

2023-12-27 15:57 UTC, vovasalyha commented on src/main/java/mate/academy/bookstore/dto/UserLoginRequestDto.java
> +    private String email;
Validate also maximum size for email, to not exceed DB schema constraints.

2023-12-27 15:59 UTC, merged